# NNCP — Create Linux bridge 'br1' on a dedicated NIC (e.g., enp8s0)
apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: br1-linux-bridge
spec:
  nodeSelector:
    node-role.kubernetes.io/worker: ''
  desiredState:
    interfaces:
    - name: br1
      description: Linux bridge with enp8s0 as a port
      type: linux-bridge
      state: up
      bridge:
        options:
          stp:
            enabled: false
        port:
        - name: enp8s0             # CHANGE_ME if NIC differs

# START: OCP Repo Fix — NNCP rollback example (state: absent)
# Example rollback (remove policy safely)
# apiVersion: nmstate.io/v1
# kind: NodeNetworkConfigurationPolicy
# metadata:
#   name: example-rollback
# spec:
#   desiredState:
#     interfaces: []
#   state: absent
# END: OCP Repo Fix — NNCP rollback example (state: absent)
