# Feel free to modify to reflect the operators/images you're targeting for your install
# To get an accurate representation of the current list of operators and their current default channels,
#   run the following command on an internet-facing box that has the oc-mirror binary available (NOTE: it takes a few minutes to complete)
#   oc-mirror list operators --catalog=registry.redhat.io/redhat/redhat-operator-index:v4.18 --version=4.18 # Replace "4.18" with whatever minor release version you're targeting for the install
kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  platform:
    # Uncommenting the following two lines and updating to reflect your specific architecture, will help decrease the size of the mirrored content.
    # architectures:
    #   - amd64
    channels:
      - type: ocp
        name: stable-4.18
        minVersion: 4.18.3
        maxVersion: 4.18.3
    graph: true
  additionalImages:
    - name: registry.redhat.io/rhel9/support-tools:latest
    - name: registry.redhat.io/rhel9/rhel-guest-image:latest
    - name: registry.redhat.io/openshift4/ose-must-gather:latest
    - name: registry.redhat.io/ubi9/ubi:latest
    - name: registry.redhat.io/odf4/odf-must-gather-rhel9:v4.18
    - name: registry.redhat.io/container-native-virtualization/cnv-must-gather-rhel9:v4.18
    # The following are for the Boot Images for various VM OS's (For OpenShift Virtualization). Feel free to remove/update as needed
    - name: registry.redhat.io/rhel8/rhel-guest-image:8.4.0
    - name: registry.redhat.io/rhel8/rhel-guest-image:8.6.0
    - name: registry.redhat.io/rhel8/rhel-guest-image:8.8.0
    - name: registry.redhat.io/rhel8/rhel-guest-image:8.10.0
    - name: registry.redhat.io/rhel8/rhel-guest-image:latest
    - name: registry.redhat.io/rhel9/rhel-guest-image:9.2
    - name: registry.redhat.io/rhel9/rhel-guest-image:9.4
    - name: registry.redhat.io/rhel9/rhel-guest-image:latest
    - name: quay.io/containerdisks/centos:7-2009
    - name: quay.io/containerdisks/centos-stream:8-latest
    - name: quay.io/containerdisks/centos-stream:9-latest
  operators:    
    # Red Hat Operator Index Catalog
    - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.18
      packages:
        # Advanced Cluster Management for Kubernetes
        - name: advanced-cluster-management
          channels:
            - name: release-2.14
        - name: multicluster-engine
          channels:
            - name: stable-2.9
        # Advanced Cluster Security for Kubernetes
        - name: rhacs-operator
          channels:
            - name: stable
        # Quay
        - name: quay-operator
          channels:
            - name: stable-3.15
        - name: quay-bridge-operator
          channels:
            - name: stable-3.15
        - name: container-security-operator
          channels:
            - name: stable-3.15
        # Data Foundation Essentials
        - name: odf-operator
          channels:
            - name: stable-4.18
        - name: odf-csi-addons-operator
          channels:
            - name: stable-4.18
        - name: ocs-operator
          channels:
            - name: stable-4.18
        - name: mcg-operator
          channels:
            - name: stable-4.18
        - name: odf-dependencies
          channels:
            - name: stable-4.18
        - name: rook-ceph-operator
          channels:
            - name: stable-4.18
        - name: recipe
          channels:
            - name: stable-4.18
        - name: cephcsi-operator
          channels:
            - name: stable-4.18
        - name: ocs-client-operator
          channels:
            - name: stable-4.18
        - name: odf-prometheus-operator
          channels:
            - name: stable-4.18
        - name: odr-cluster-operator
          channels:
            - name: stable-4.18
        - name: odr-hub-operator
          channels:
            - name: stable-4.18
        # Local Storage Operator
        - name: lvms-operator
          channels:
            - name: stable-4.18
        - name: local-storage-operator
          channels:
            - name: stable
        # Web Terminal
        - name: web-terminal
          channels:
            - name: fast
        - name: devworkspace-operator
          channels:
            - name: fast
        # Virtualization
        - name: kubevirt-hyperconverged
          channels:
            - name: stable
        - name: kubernetes-nmstate-operator
          channels:
            - name: stable
        # Migration Toolkit for Virtualization
        - name: mtv-operator
         channels:
            - name: release-v2.9
        # Update Service
        - name: cincinnati-operator
          channels:
            - name: v1
        # Compliance Operator
        - name: compliance-operator
          channels:
            - name: stable
        # File Integrity Operator
        - name: file-integrity-operator
          channels:
            - name: stable
        # Ansible Automation Platform Operator
        - name: ansible-automation-platform-operator
          channels:
            - name: stable-2.5
        # MetalLB Operator
        - name: metallb-operator
          channels:
            - name: stable
        # PTP Operator
        - name: ptp-operator
          channels:
            - name: stable
        # OpenShift Logging
        - name: cluster-logging
          channels:
            - name: stable-6.3
        - name: loki-operator
          channels:
            - name: stable-6.3
        # OpenShift Service Mesh
        - name: servicemeshoperator3
          channels:
            - name: stable
        - name: kiali-ossm
          channels:
            - name: stable
        - name: jaeger-product
          channels:
            - name: stable
        # Cluster Observability Operator
        - name: cluster-observability-operator
          channels:
            - name: stable
        # Network Observability Operator
        - name: netobserv-operator
          channels:
            - name: stable
        # Keycloak Operator
        - name: rhbk-operator
          channels:
            - name: stable-v26.0
        # Cert Manager
        - name: openshift-cert-manager-operator
          channels:
            - name: stable-v1

    # Red Hat Community Operator Index Catalog
    - catalog: registry.redhat.io/redhat/community-operator-index:v4.18
      packages:
        # Trident
        - name: group-sync-operator
          channels:
            - name: alpha

    # Red Hat Certified Operator Index Catalog     
    - catalog: registry.redhat.io/redhat/certified-operator-index:v4.18
      packages:
        # NVIDIA GPU Operator
        - name: gpu-operator-certified
          channels:
            - name: v25.3
        # Trident
        - name: trident-operator
          channels:
            - name: stable
