# -----------------------------------------------------------------------------
# IMPORTANT PREP
# - sshKey MUST be a PUBLIC key (e.g., ~/.ssh/id_ed25519.pub). Generate if needed:
#     ssh-keygen -t ed25519 -C "you@host" -f ~/.ssh/id_ed25519
# - pullSecret MUST be single-line JSON:
#     tr -d '\n' < pull-secret.json
#     # or
#     jq -c . < pull-secret.json
# - Connected: use your Red Hat pull secret from console.redhat.com
# - Disconnected: include ONLY your mirror registry auth in pullSecret (single-line JSON).
#   NOTE: If you truly lack creds, OKD documents a dummy pattern for OKD (NOT SUPPORTED for OCP).
# - Custom CA? Paste into additionalTrustBundle and set additionalTrustBundlePolicy: Always.
# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# AGENT INSTALLER NOTES
# - Use:  openshift-install agent create image
#         # boot hosts with the generated ISO (or PXE/iPXE per docs)
# - agent-config.yaml uses NMState for host networking in 'networkConfig'.
# - If all hosts use DHCP and you provide at least one static IP in networkConfig,
#   you may omit rendezvousIP; otherwise set it explicitly.
# -----------------------------------------------------------------------------
apiVersion: v1
baseDomain: example.com
metadata:
  name: cluster

networking:
  networkType: OVNKubernetes
  machineNetwork:
  - cidr: 10.90.0.0/24
#   clusterNetwork:            # OPTIONAL: override default pod network
#   - cidr: 10.128.0.0/14
#     hostPrefix: 23
#   serviceNetwork:            # OPTIONAL: override default service CIDR
#   - 172.30.0.0/16

controlPlane:
  name: master
  replicas: 3

compute:
- name: worker
  replicas: 3

sshKey: 'ssh-ed25519 AAAA...REPLACE_ME... user@host'
pullSecret: '{"auths":{"registry.example.com":{"auth":"REPLACE_BASE64","email":"you@example.com"}}}'

platform:
  baremetal:
    apiVIPs:
    - 10.90.0.10
    ingressVIPs:
    - 10.90.0.11

imageDigestSources:              # Disconnected installs: REQUIRED (use your mirror)
- mirrors:
  - registry.example.com/ocp/release
  source: quay.io/openshift-release-dev/ocp-release
- mirrors:
  - registry.example.com/ocp/release-images
  source: quay.io/openshift-release-dev/ocp-v4.0-art-dev

# additionalTrustBundlePolicy: Always   # optional (required if your mirror has a custom CA)
# additionalTrustBundle: |              # optional - paste PEM here matching the mirror above
#   -----BEGIN CERTIFICATE-----
#   ...
#   -----END CERTIFICATE-----

# imageContentSources:             # (Deprecated) Only if you mirrored with oc-mirror v1 and must use it temporarily
# - mirrors:
#   - registry.example.com/ocp/release
#   source: quay.io/openshift-release-dev/ocp-release
# - mirrors:
#   - registry.example.com/ocp/release-images
#   source: quay.io/openshift-release-dev/ocp-v4.0-art-dev

# proxy:              # If proxied access is required, uncomment and populate this block
#   httpProxy: http://user:pass@proxy.example.com:3128              # httpProxy/httpsProxy may include creds; httpsProxy CAN point to http:// if your proxy terminates TLS
#   httpsProxy: http://user:pass@proxy.example.com:3128              # httpProxy/httpsProxy may include creds; httpsProxy CAN point to http:// if your proxy terminates TLS
#   noProxy: ".cluster.example.com,.example.com,127.0.0.1,localhost,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"  # noProxy should include your cluster domain(s), service networks, and RFC1918 ranges as needed

# capabilities: {}           # OPTIONAL: limit/enable cluster capabilities

# fips: false                # OPTIONAL: set true for FIPS-mode installs
