---
kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v1alpha2
additionalImages:
  - name: registry.redhat.io/rhel9/support-tools:latest
  - name: registry.redhat.io/openshift4/ose-must-gather:latest
  - name: registry.redhat.io/ubi9/ubi:latest
