# -----------------------------------------------------------------------------
# IMPORTANT PREP
# - sshKey MUST be a PUBLIC key (e.g., ~/.ssh/id_ed25519.pub). Generate if needed:
#     ssh-keygen -t ed25519 -C "you@host" -f ~/.ssh/id_ed25519
#     cat ~/.ssh/id_ed25519.pub
# - pullSecret MUST be single-line JSON. Examples:
#     tr -d '\n' < pull-secret.json
#     # or
#     jq -c . < pull-secret.json
# - Connected installs: use your Red Hat pull secret from console.redhat.com
# - Disconnected installs: include ONLY your mirror registry auth in pullSecret.
#   NOTE: OKD has a dummy pattern for OKD only (NOT SUPPORTED for OCP).
# - If your environment uses a custom CA (proxy or mirror), paste it into additionalTrustBundle
#   and set additionalTrustBundlePolicy: Always
# -----------------------------------------------------------------------------
apiVersion: v1
baseDomain: example.com
metadata:
  name: cluster

networking:
  networkType: OVNKubernetes
  machineNetwork:
  - cidr: 10.90.0.0/24

controlPlane:
  name: master
  replicas: 3

compute:
- name: worker
  replicas: 3

sshKey: 'ssh-ed25519 AAAA...REPLACE_ME... user@host'

pullSecret: '{"auths":{"registry.redhat.io":{"auth":"REPLACE_BASE64","email":"you@example.com"}}}'

# UPI: the installer does not manage cloud load balancers.
platform:
  none: {}  # Provide external LB + DNS (api, api-int, and *.apps)

# For expected DNS/LB targets:
#   api.cluster.example.com
#   api-int.cluster.example.com
#   *.apps.cluster.example.com

# imageDigestSources:              # Disconnected installs (preferred; replaces deprecated imageContentSources)
# - mirrors:
#   - registry.example.com/ocp/release
#   source: quay.io/openshift-release-dev/ocp-release
# - mirrors:
#   - registry.example.com/ocp/release-images
#   source: quay.io/openshift-release-dev/ocp-v4.0-art-dev
#
# imageContentSources:             # (Deprecated) Provide only if you mirrored with oc-mirror v1 and must use it temporarily
# - mirrors:
#   - registry.example.com/ocp/release
#   source: quay.io/openshift-release-dev/ocp-release

