# -----------------------------------------------------------------------------
# IMPORTANT PREP
# - UPI on vSphere: YOU provision VMs/LBs/DNS; installer generates Ignition.
# -----------------------------------------------------------------------------
apiVersion: v1
baseDomain: example.com
metadata:
  name: cluster-proxied

networking:
  networkType: OVNKubernetes
  machineNetwork:
  - cidr: 10.90.0.0/24

controlPlane:
  name: master
  replicas: 3
compute:
- name: worker
  replicas: 3

sshKey: 'ssh-ed25519 AAAA...REPLACE_ME... user@host'
pullSecret: '{"auths":{"registry.redhat.io":{"auth":"REPLACE_BASE64","email":"you@example.com"}}}'

platform:
  none: {}  # UPI

proxy:                              # ENABLED
  httpProxy: http://user:pass@proxy.example.com:3128
  httpsProxy: http://user:pass@proxy.example.com:3128
  noProxy: ".cluster.example.com,.example.com,.svc,.cluster.local,127.0.0.1,localhost,10.90.0.0/24"

additionalTrustBundle: |
  -----BEGIN CERTIFICATE-----
  MIID...REPLACE_ME...
  -----END CERTIFICATE-----
additionalTrustBundlePolicy: Always

# imageDigestSources:              # Optional (disconnected)
# - mirrors:
#   - registry.example.com/ocp/release
#   source: quay.io/openshift-release-dev/ocp-release
# - mirrors:
#   - registry.example.com/ocp/release-images
#   source: quay.io/openshift-release-dev/ocp-v4.0-art-dev
