apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: bond0-with-vlans
spec:
  desiredState:
    interfaces:
      - name: bond0
        type: bond
        state: up
        link-aggregation:
          mode: balance-rr
          port:
            - ens3
            - ens4
      - name: vlan100
        type: vlan
        state: up
        vlan:
          base-iface: bond0
          id: 100
      - name: vlan200
        type: vlan
        state: up
        vlan:
          base-iface: bond0
          id: 200
