# -----------------------------------------------------------------------------
# IMPORTANT PREP
# - sshKey MUST be a PUBLIC key (e.g., ~/.ssh/id_ed25519.pub). Generate if needed:
#     ssh-keygen -t ed25519 -C "you@host" -f ~/.ssh/id_ed25519
#     cat ~/.ssh/id_ed25519.pub
# - pullSecret MUST be single-line JSON. Examples:
#     tr -d '\n' < pull-secret.json
#     # or
#     jq -c . < pull-secret.json
# - Connected installs: use your Red Hat pull secret from console.redhat.com
# - Disconnected installs: include ONLY your mirror registry auth in pullSecret (single-line JSON).
# - If your environment uses a custom CA (proxy or mirror), paste it into additionalTrustBundle
#   and set additionalTrustBundlePolicy: Always
# -----------------------------------------------------------------------------
apiVersion: v1
baseDomain: example.com
metadata:
  name: cluster

# fips: true  # Optional

networking:
  networkType: OVNKubernetes
  machineNetwork:
  - cidr: 10.90.0.0/24

controlPlane:
  name: master
  replicas: 3

compute:
- name: worker
  replicas: 3

sshKey: 'ssh-ed25519 AAAA...REPLACE_ME... user@host'
pullSecret: '{"auths":{"registry.redhat.io":{"auth":"REPLACE_BASE64","email":"you@example.com"}}}'

platform:
  vsphere:
    # Modern, multi-domain schema (preferred for 4.18)
    vcenters:
    - server: vcenter.example.com
      user: administrator@vsphere.local
      password: REPLACE_ME
      datacenters:
      - DC1
    failureDomains:
    - name: fd-a
      region: region1
      zone: zone-a
      server: vcenter.example.com
      topology:
        datacenter: DC1
        # Use absolute inventory paths where required by docs
        computeCluster: /DC1/host/Compute-Cluster-A
        resourcePool: /DC1/host/Compute-Cluster-A/Resources/openshift   # optional but recommended
        folder: /DC1/vm/openshift                                       # optional
        datastore: /DC1/datastore/datastore1
        networks:
        - "VM Network"     # PortGroup available on ESXi in this domain
    - name: fd-b
      region: region1
      zone: zone-b
      server: vcenter.example.com
      topology:
        datacenter: DC1
        computeCluster: /DC1/host/Compute-Cluster-B
        resourcePool: /DC1/host/Compute-Cluster-B/Resources/openshift
        folder: /DC1/vm/openshift
        datastore: /DC1/datastore/datastore2
        networks:
        - "VM Network"
    - name: fd-c
      region: region1
      zone: zone-c
      server: vcenter.example.com
      topology:
        datacenter: DC1
        computeCluster: /DC1/host/Compute-Cluster-C
        resourcePool: /DC1/host/Compute-Cluster-C/Resources/openshift
        folder: /DC1/vm/openshift
        datastore: /DC1/datastore/datastore3
        networks:
        - "VM Network"

    # VIPs are REQUIRED for multi-node vSphere IPI
    apiVIPs:
    - 10.90.0.10
    ingressVIPs:
    - 10.90.0.11

    # diskType: thin          # Optional
    # tags:                    # Optional: vSphere tags to apply to created VMs
    # - key: owner
    #   value: platform-team

# additionalTrustBundle: |         # Optional: proxy/registry CA PEM
#   -----BEGIN CERTIFICATE-----
#   MIID...REPLACE_ME...
#   -----END CERTIFICATE-----
# additionalTrustBundlePolicy: Always

# imageDigestSources:              # Disconnected installs (preferred)
# - mirrors:
#   - registry.example.com/ocp/release
#   source: quay.io/openshift-release-dev/ocp-release
# - mirrors:
#   - registry.example.com/ocp/release-images
#   source: quay.io/openshift-release-dev/ocp-v4.0-art-dev
#
# imageContentSources:             # (Deprecated) legacy v1 mapping
# - mirrors:
#   - registry.example.com/ocp/release
#   source: quay.io/openshift-release-dev/ocp-release
