# Minimal dnsmasq.conf example for OpenShift lab use
domain-needed
bogus-priv
no-resolv
server=1.1.1.1
server=8.8.8.8

# Replace example.local with your baseDomain
domain=example.local

# API and Ingress VIPs
address=/api.gold/192.168.111.5
address=/.apps.gold.example.local/192.168.111.6

# Host records (add control plane and workers)
host-record=cp-0.gold.example.local,192.168.111.10
host-record=cp-1.gold.example.local,192.168.111.11
host-record=cp-2.gold.example.local,192.168.111.12
ptr-record=10.111.168.192.in-addr.arpa,cp-0.gold.example.local
ptr-record=11.111.168.192.in-addr.arpa,cp-1.gold.example.local
ptr-record=12.111.168.192.in-addr.arpa,cp-2.gold.example.local
