---
# VM example for Option 2: use the OVN localnet NAD on the dedicated OVS bridge
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm-br0-net
  namespace: vmtest
spec:
  running: true
  template:
    metadata:
      labels:
        example: br0-ovs-localnet
    spec:
      networks:
        - name: br0-net
          multus:
            networkName: vmtest/br0-network
      domain:
        devices:
          interfaces:
            - name: br0-net
              bridge: {}
        resources:
          requests:
            memory: 2Gi
            cpu: 2
      volumes:
        - name: rootdisk
          containerDisk:
            image: quay.io/containerdisks/centos-stream:9-latest
