apiVersion: agent-install.openshift.io/v1beta1
kind: AgentConfig
metadata:
  name: cluster
rendezvousIP: 10.90.0.20
# additionalNTPSources:
# - 10.90.0.2
hosts:
- hostname: cluster-master-1
  role: master
  interfaces:
  - name: eno1
    macAddress: 52:54:00:aa:m1:01
  rootDeviceHints:
    deviceName: "/dev/disk/by-path/pci-0000:01:00.0-nvme-1"
  networkConfig:
    interfaces:
    - name: eno1
      type: ethernet
      state: up
      ipv4:
        enabled: true
        address:
        - 10.90.0.21/24
        gateway: 10.90.0.1
      ipv6:
        enabled: false
