# NAD — OVN localnet referencing the 'br-ex-network' localnet above
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: br-ex-network
  namespace: vmtest
spec:
  config: |
    {
      "cniVersion": "0.4.0",
      "type": "ovn-k8s-cni-overlay",
      "topology": "localnet",
      "name": "br-ex-network",
      "netAttachDefName": "vmtest/br-ex-network"
    }
