# NNCP — add an OVN localnet mapping on br-ex (single NIC scenario)
# Safe pattern: do not reconfigure br-ex itself; just add a localnet mapping.
apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: br-ex-network
spec:
  nodeSelector:
    node-role.kubernetes.io/worker: ''
  desiredState:
    ovn:
      bridge-mappings:
      - localnet: br-ex-network   # NAME referenced by the NAD below
        bridge: br-ex             # Built-in bridge for OVN-Kubernetes
        state: present            # use 'absent' to remove safely

# START: OCP Repo Fix — NNCP rollback example (state: absent)
# Example rollback (remove policy safely)
# apiVersion: nmstate.io/v1
# kind: NodeNetworkConfigurationPolicy
# metadata:
#   name: example-rollback
# spec:
#   desiredState:
#     interfaces: []
#   state: absent
# END: OCP Repo Fix — NNCP rollback example (state: absent)
