---
# Example: Access external networks using macvtap (L2 bridge to host NIC)
# Docs: https://www.redhat.com/en/blog/access-external-networks-with-openshift-virtualization
apiVersion: kubevirt.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: macvtap-external
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "type": "macvtap",
      "master": "ens3f0",
      "mode": "bridge"
    }
