---
# Example: Access external networks using SR-IOV (dedicated VF to VM)
# Docs: https://www.redhat.com/en/blog/access-external-networks-with-openshift-virtualization
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetwork
metadata:
  name: sriov-external
  namespace: openshift-sriov-network-operator
spec:
  resourceName: sriov_netdevice
  networkNamespace: default
  ipam: |
    {
      "type": "static",
      "addresses": [
        { "address": "192.0.2.10/24", "gateway": "192.0.2.1" }
      ]
    }
