# Feel free to modify to reflect the operators/images you're targeting for your install
# To get an accurate representation of the current list of operators and their current default channels,
#   run the following command on an internet-facing box that has the oc-mirror binary available (NOTE: it takes a few minutes to complete)
#   oc-mirror list operators --catalog=registry.redhat.io/redhat/redhat-operator-index:v4.20 --version=4.20 # Replace "4.20" with whatever minor release version you're targeting for the install
kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  operators:
    # Red Hat Operator Index Catalog
    - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.20
      packages:
        # Advanced Cluster Management for Kubernetes
        - name: advanced-cluster-management
          channels:
            - name: release-2.14
        - name: multicluster-engine
          channels:
            - name: stable-2.9
        # Advanced Cluster Security for Kubernetes
        - name: rhacs-operator
          channels:
            - name: stable
        # Quay
        - name: quay-operator
          channels:
            - name: stable-3.15
        - name: quay-bridge-operator
          channels:
            - name: stable-3.15
        - name: container-security-operator
          channels:
            - name: stable-3.15
        # Data Foundation Essentials
        - name: odf-operator
          channels:
            - name: stable-4.19
        - name: odf-csi-addons-operator
          channels:
            - name: stable-4.20
        - name: ocs-operator
          channels:
            - name: stable-4.19
        - name: mcg-operator
          channels:
            - name: stable-4.19
        - name: odf-dependencies
          channels:
            - name: stable-4.20
        - name: rook-ceph-operator
          channels:
            - name: stable-4.19
        - name: recipe
          channels:
            - name: stable-4.20
        - name: cephcsi-operator
          channels:
            - name: stable-4.20
        - name: ocs-client-operator
          channels:
            - name: stable-4.20
        - name: odf-prometheus-operator
          channels:
            - name: stable-4.20
        - name: odr-cluster-operator
          channels:
            - name: stable-4.20
        - name: odr-hub-operator
          channels:
            - name: stable-4.20
        # Local Storage Operator
        - name: lvms-operator
          channels:
            - name: stable-4.19
        - name: local-storage-operator
          channels:
            - name: stable
        # Web Terminal
        - name: web-terminal
          channels:
            - name: fast
        - name: devworkspace-operator
          channels:
            - name: fast
        # Virtualization
        - name: kubevirt-hyperconverged
          channels:
            - name: stable
        - name: kubernetes-nmstate-operator
          channels:
            - name: stable
        # Migration Toolkit for Virtualization
        - name: mtv-operator
         channels:
            - name: release-v2.9
        # Update Service
        - name: cincinnati-operator
          channels:
            - name: v1
        # Compliance Operator
        - name: compliance-operator
          channels:
            - name: stable
        # File Integrity Operator
        - name: file-integrity-operator
          channels:
            - name: stable
        # Ansible Automation Platform Operator
        - name: ansible-automation-platform-operator
          channels:
            - name: stable-2.5
        # MetalLB Operator
        - name: metallb-operator
          channels:
            - name: stable
        # PTP Operator
        - name: ptp-operator
          channels:
            - name: stable
        # OpenShift Logging
        - name: cluster-logging
          channels:
            - name: stable-6.3
        - name: loki-operator
          channels:
            - name: stable-6.3
        # OpenShift Service Mesh
        - name: servicemeshoperator3
          channels:
            - name: stable
        - name: kiali-ossm
          channels:
            - name: stable
        - name: jaeger-product
          channels:
            - name: stable
        # Cluster Observability Operator
        - name: cluster-observability-operator
          channels:
            - name: stable
        # Network Observability Operator
        - name: netobserv-operator
          channels:
            - name: stable
        # Keycloak Operator
        - name: rhbk-operator
          channels:
            - name: stable-v26.0
        # Cert Manager
        - name: openshift-cert-manager-operator
          channels:
            - name: stable-v1

    # Red Hat Community Operator Index Catalog
    - catalog: registry.redhat.io/redhat/community-operator-index:v4.20
      packages:
        # Trident
        - name: group-sync-operator
          channels:
            - name: alpha

    # Red Hat Certified Operator Index Catalog     
    - catalog: registry.redhat.io/redhat/certified-operator-index:v4.20
      packages:
        # NVIDIA GPU Operator
        - name: gpu-operator-certified
          channels:
            - name: v25.3
        # Trident
        - name: trident-operator
          channels:
            - name: stable
